env:
  matrix:
  - CABALVER=1.18 GHCVER=7.6.3
  - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=head GHCVER=head
matrix:
  allow_failures:
  - env: CABALVER=head GHCVER=head
deploy:
  provider: hackage
  username: HiromiIshii
  password:
    secure: Yrrwoeh7ExqZp85v0cBEbRv4qJSn07t+xtKVOTVTZBpe3lEnzvThE8JneCV9gskZrprhSWev9izdTxpFwDZH/LJUsSVIOapsDxjlsUQKW3U7BpQrfalSgMAPhRX/YMevTwqssDD2jltqSddhWFM0lgtZ586j0lsH6PMl4wI5Rg8=
  on:
    repo: konn/type-natural
    tags: true
    condition: $GHCVER = 7.8.4
    all_branches: true
before_install:
- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
install:
- cabal --version
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo
  '?')]"
- travis_retry cabal update
- cabal install --only-dependencies --enable-tests --enable-benchmarks
script:
- if [ -f configure.ac ]; then autoreconf -i; fi
- cabal configure --enable-tests --enable-benchmarks -v2
- cabal build
- cabal test
- cabal check
- cabal sdist
- export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ; cd dist/; if
  [ -f "$SRC_TGZ" ]; then cabal install --force-reinstalls "$SRC_TGZ"; else echo "expected
  '$SRC_TGZ' not found"; exit 1; fi
